AllCops:
  NewCops: enable

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/Next:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/InverseMethods:
  Enabled: false
