#!/usr/bin/env ruby

# Copyright © 2020-2021 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require 'optparse'
require 'yaml'
require 'json'
require 'base64'

$CLEAN = false
$DOC = false
$RECIPE = nil
$LIST = false
$WARN = false
$EXPORT = false
$BUILD = nil
$IN = nil

parser = OptionParser.new do |opts|
  opts.summary_indent = '  '
  opts.summary_width = 24
  opts.banner = 'Usage: build [options]'
  opts.separator ''
  opts.separator 'Options (handled in presented order):'
  opts.on('--clean', 'Ignore embedded information.') { $CLEAN = true }
  opts.on('--document', 'Print default values and information.') { $DOC = true }
  opts.on('--import FILELIST', 'Piece YAML file list as YAML array.') { |f| $RECIPE = f }
  opts.on('--list', 'List the names that are available.') { $LIST = true }
  opts.on('--warn', 'Warn about missing requirements instead of an error.') { $WARN = true }
  opts.on('--export', 'Export data to current directory as separate files.') { $EXPORT = true }
  opts.on('--build OUTPUT', 'Re-build to named script.') { |f| $BUILD = f }
  opts.on('-i', '--input FILENAME', 'Specifications to use.') { |f| $IN = f }
  opts.on('-h', '--help', 'Print this help and exit.') do
    $stdout.puts opts
    exit 0
  end
end
parser.parse!

#PIECESASSIGNMENTSTART#
$PIECES = {}
$FILECONTENTS = {}
#PIECESASSIGNMENTEND#

if $CLEAN
  $PIECES = {}
  $FILECONTENTS = {}
end

$FILECONTENTS.each_pair do |key, value|
  $FILECONTENTS[key] = Base64.decode64(value)
end

$DEFAULT = %(---
piece:
  includes: [] # Lines or blocks of (conditional) includes inserted in header.
  source_includes: [] # As above but inserted in source file.
  requires: [] # Other piece names that are required.
  writer: false # Only true for pieces that have Write-function template.
  scalar: true # True when piece parses a simple scalar value (int, string).
  external: true # True when user can use the piece name in input specification.
  declaration: ~ # Forward declaration for header file.
  parsername: ~ # Parser class name.
  pooled: ~ # ParserPool index replaces this string for parsers that use pool.
  # These can only be given if pooled is not specified.
  poolindexes: ~ # ParserPool Parsers enum contents replace this string.
  poolparsers: ~ # ParserPool Parser tuple contents replace this string.
  poolparsertypes: ~ # ParserPool Value tuple contents replace this string.
specification:
  namespace: specjson # Name space for output files.
  full: false # Include unused parsers.
  requires: [] # Pieces that are needed by code but not specified in types.
  types: { } # Type names mapped to field specification objects.
  generate: { } # Type names from types mapped to code generate instructions.
  header_extension: hpp # Header file name extension. Used if header not given.
  source_extension: cpp # Source file name extension. Used if source not given.
  header: ~ # Specification name.header_extension unless given.
  source: ~ # Specification name.source_extension unless given.
types: # An object with field name mapped to object below.
  format: REQUIRED # Piece name string or array of piece names.
  required: true # Indicates whether field must be present in object.
  checker: ~ # String inserted to code to check optional field in Write.
  accessor: ~ # String inserted to code to get field value in Write.
generate:
  parser: false # Produce parser code for the type.
  writer: false # Produce Write function and template for the type.
)

puts($DEFAULT) if $DOC

$DEFAULT = YAML.safe_load($DEFAULT)

def aargh(message, exit_code = nil)
  $stderr.puts message
  exit exit_code unless exit_code.nil?
end

def load_piece_file(piece, field, directory)
  filename = piece.fetch(field, nil)
  if filename.nil?
    piece[field] = nil
    piece["#{field}_stored"] = nil
    return
  end
  begin
    filename = File.realpath(filename, directory)
    puts filename
    f = File.new(filename, 'r')
    content = IO.read(f)
    f.close
  rescue StandardError
    aargh("Failed to open/read: #{filename}", 3)
  end
  stored = $FILECONTENTS.key(content)
  if stored.nil?
    stored = "c#{$FILECONTENTS.size}"
    $FILECONTENTS[stored] = content
  end
  piece["#{field}_stored"] = stored
end

def defaults(kind, spec)
  $DEFAULT[kind].each_pair do |field, value|
    if spec.key? field
      if value.is_a?(Array) && !spec[field].is_a?(Array)
        spec[field] = [ spec[field] ]
      end
    else
      spec[field] = value
    end
  end
end

def default(spec, field, value)
  spec[field] = value unless spec.key? field
end

def check_given(spec, kind, field, error)
  aargh(error, 4) unless spec[field] != $DEFAULT[kind][field]
end

def load_spec(filename, root = nil)
  begin
    unless root.nil?
      filename = File.realpath(filename, root)
      puts filename
    end
    f = File.open(filename, 'r')
    input = IO.read(f)
    f.close
  rescue StandardError
    aargh("Failed to find/read #{filename}", 3)
  end
  begin
    specs = JSON.parse(input)
  rescue StandardError
    begin
      specs = YAML.safe_load(input, aliases: true)
    rescue StandardError
      aargh("#{filename} neither JSON nor YAML.", 3)
    end
  end
  specs
end

unless $RECIPE.nil?
  recipe = load_spec($RECIPE)
  root = File.dirname(File.realpath($RECIPE))
  unless recipe.is_a? Array
    aargh('Recipe file must be a YAML array of file names.', 2)
  end
  recipe.each do |filename|
    piece = load_spec(filename, root)
    d = File.dirname(File.realpath(filename, root))
    piece.each_pair do |name, spec|
      load_piece_file(spec, 'header', d)
      load_piece_file(spec, 'source', d)
      load_piece_file(spec, 'license', d)
      defaults('piece', spec)
      spec['external'] = false if spec['external'] && spec['writer']
      if spec['external']
        check_given(spec, 'piece', 'parsername', "#{filename} #{name} has no 'parsername'")
      end
      unless spec['pooled'].nil?
        %w[poolindexes poolparsers poolparsertypes].each do |field|
          raise ArgumentError "#{name} has both pooled and #{field}" unless spec[field].nil?
        end
      end
      puts("Replacing #{name}") if $PIECES.key? name
      $PIECES[name] = spec
    end
  end
end

if $LIST
  all = []
  $PIECES.each_pair do |name, piece|
    all.push("#{name}#{piece['external'] ? '' : ' (internal)'}")
  end
  all.sort!
  puts all
end

# Check that requirements are met.
missing = false
$PIECES.each_pair do |name, spec|
  spec['requires'].each do |r|
    unless $PIECES.key? r
      aargh("#{name} missing requirement: #{r}")
      missing = true
    end
  end
end
exit(4) if missing && !$WARN

if $EXPORT
  pieces = {}
  name2store = {}
  $PIECES.each_pair do |name, piece|
    piece = piece.clone
    %w[header source license].each do |field|
      next if piece[field].nil?
      b = File.basename piece[field]
      s = piece["#{field}_stored"]
      if name2store.key? b
        name2store[b].push(s) unless name2store[b].include? s
      else
        name2store[b] = [ s ]
      end
      piece[field] = b
    end
    pieces[name] = piece
  end
  collisions = []
  name2store.each_pair do |b, s|
    if s.size == 1
      f = File.new(b, 'w')
      f.write($FILECONTENTS[s[0]])
      f.close
    else
      collisions.push b
    end
  end
  store2name = {}
  collisions.each do |b|
    s = name2store[b]
    name2store.delete b
    pre = File.basename(b, '.*')
    ext = b.slice(pre.size, b.size - pre.size)
    idx = 0
    bn = b
    s.each do |c|
      while name2store.key? bn
        idx += 1
        bn = "#{pre}_#{idx}#{ext}"
      end
      store2name[c] = bn
      f = File.new(bn, 'w')
      f.write($FILECONTENTS[c])
      f.close
      name2store[bn] = [ c ]
    end
  end
  list = []
  pieces.each_pair do |name, piece|
    %w[header source license].each do |field|
      if piece[field].nil?
        piece.delete field
      else
        s = piece["#{field}_stored"]
        piece[field] = store2name[s] if store2name.key? s
      end
      piece.delete "#{field}_stored"
    end
    list.push "#{name}.yaml"
    f = File.new(list.last, 'w')
    f.write(YAML.dump({ name => piece }))
    f.close
  end
  f = File.new('exported.yaml', 'w')
  f.write(YAML.dump(list))
  f.close
end

unless $BUILD.nil?
  script = File.new($PROGRAM_NAME, chomp: true).readlines
  first = script.find_index { |ln| ln.start_with? '#PIECESASSIGNMENTSTART#' }
  last = script.find_index { |ln| ln.start_with? '#PIECESASSIGNMENTEND#' }
  if first.nil? || last.nil? || last < first
    aargh('Failed to find lines starting with, or in wrong order: #PIECESASSIGNMENTSTART# #PIECESASSIGNMENTEND#', 2)
  end
  succeeding = script.slice(last, script.size - last).join
  script = script.slice(0, first + 1).join
  encoded = {}
  $FILECONTENTS.each_pair do |key, value|
    encoded[key] = Base64.encode64(value)
  end
  script.concat(%(
$PIECES = YAML.safe_load(%(#{YAML.dump($PIECES)}), aliases: true)
$FILECONTENTS = YAML.safe_load(%(#{YAML.dump(encoded)}), aliases: true)
))
  script.concat(succeeding)
  IO.write($BUILD, script)
  File.chmod(0o755, $BUILD)
end

exit(0) if $IN.nil?

specs = load_spec($IN)

$PIECES.each_pair { |name, piece| piece['name'] = name }

def all_requirements(piece, reqs)
  unless reqs.include? piece['name']
    reqs.push piece['name']
    piece['requires'].each do |r|
      all_requirements($PIECES[r], reqs) unless reqs.include? r
    end
  end
  reqs
end

$PIECES.each_value do |piece|
  piece['all_requires'] = all_requirements(piece, [])
end

def parserpool_substitutions(needed, namespace)
  $pools = []
  $pooled = []
  needed.each do |name|
    piece = $PIECES[name]
    $pools.push(name) unless piece['poolindexes'].nil? && piece['poolparsers'].nil? && piece['poolparsertypes'].nil?
    $pooled.push(name) unless piece['pooled'].nil?
    %w[header source].each do |field|
      fc = piece["#{field}_stored"]
      next if fc.nil?
      piece["#{field}_content"] = String.new($FILECONTENTS[fc])
      next if 'specjson' == namespace
      until piece["#{field}_content"].sub!('specjson::', "#{namespace}::").nil?
      end
    end
  end
  poolvals = {
    'poolindexes' => [],
    'poolparsers' => [],
    'poolparsertypes' => []
  }
  $pooled.each_index do |k|
    piece = $PIECES[$pooled[k]]
    poolvals['poolindexes'].push $pooled[k]
    poolvals['poolparsers'].push piece['parsername']
    poolvals['poolparsertypes'].push "#{piece['parsername']}::Type"
    [ 'header', 'source' ].each do |field|
      fc = piece["#{field}_stored"]
      next if fc.nil?
      until piece["#{field}_content"].sub!(piece['pooled'], k.to_s).nil?
      end
    end
  end
  poolvals.each_pair { |k, v| poolvals[k] = v.join(', ') }
  $pools.each do |name|
    piece = $PIECES[name]
    %w[header source].each do |field|
      fc = piece["#{field}_stored"]
      next if fc.nil?
      poolvals.each_pair do |fld, value|
        until piece["#{field}_content"].sub!(piece[fld], value).nil?
        end
      end
    end
  end
  $pooledreqs = []
  $pooled.each do |name|
    piece = $PIECES[name]
    piece['all_requires'].each do |p|
      $pooledreqs.push p unless p == name
    end
  end
  $pooledreqs.uniq!
end

def licenses(needed)
  lic2id = { }
  needed.each do |name|
    lic = $PIECES[name]['license_stored']
    next if lic.nil? || lic2id.key?(lic)
    lic2id[lic] = "License #{lic2id.size + 1}"
  end
  lic2id
end

def compare_pieces(a, b)
  a = $PIECES[a]
  b = $PIECES[b]
  # Group writers at the end.
  if a['writer']
    return 1 unless b['writer']
  else
    return -1 if b['writer']
  end
  areqs = a['all_requires']
  breqs = b['all_requires']
  if areqs.include? b['name']
    return areqs.length <=> breqs.length if breqs.include? a['name']
    return 1
  end
  return -1 if breqs.include? a['name']
  if a['writer'] && b['writer']
    if a['scalar']
      return -1 unless b['scalar']
    else
      return 1 if b['scalar']
    end
  end
  # Neither requires the other. Keep pools and pooled items before others.
  if $pooledreqs.include? a['name']
    return -1 unless $pooledreqs.include? b['name']
  else
    return 1 if $pooledreqs.include? b['name']
  end
  if $pooled.include? a['name']
    return -1 unless $pooled.include? b['name']
  else
    return 1 if $pooled.include? b['name']
  end
  if $pools.include? a['name']
    return -1 unless $pools.include? b['name']
  else
    return 1 if $pools.include? b['name']
  end
  return areqs.length <=> breqs.length unless areqs.length == breqs.length
  a['name'] <=> b['name']
end

def arrange_needed(needed)
  pools = needed.select { |name| $pools.include? name }
  others = needed.reject { |name| pools.include?(name) }
  others.sort! { |a, b| compare_pieces(a, b) }
  last = others.rindex { |name| $pooled.include? name }
  needed = others.slice!(0, last + 1)
  others.concat pools
  others.sort! { |a, b| compare_pieces(a, b) }
  needed.concat others
  needed
end

def unique_in_order(piece_names, field)
  values = []
  piece_names.each do |name|
    piece = $PIECES[name]
    next if piece[field].nil?
    if piece[field].is_a? String
      values.push(piece[field]) unless values.include? piece[field]
    else
      piece[field].each do |line|
        values.push(line) unless values.include? line
      end
    end
  end
  values
end

def license_block(lic2id)
  blocks = []
  lic2id.each_pair do |lic, id|
    blocks.push %(
#if 0
/*
#{id}:

#{$FILECONTENTS[lic]}
*/
#endif
)
  end
  blocks.join("\n")
end

def make_header(spec, piece_names, generated, lic2id)
  h = File.new(spec['header'], 'w')
  h.puts %(// Auto-generated file. Do not edit.
#if !defined(#{spec['header'].upcase.sub('.', '_')})
#define #{spec['header'].upcase.sub('.', '_')}

#{license_block(lic2id)}
)
  h.puts %(
#{unique_in_order(piece_names, 'includes').join("\n")}

namespace #{spec['namespace']} {

#{unique_in_order(piece_names, 'declaration').join("\n")}
#{(generated.keys.map { |k| generated[k][:forward].join("\n") }).join("\n")}
)
  prev = nil
  piece_names.each do |name|
    piece = $PIECES[name]
    next if piece['header_stored'].nil?
    lic = piece['license_stored']
    if lic != prev
      h.puts
      h.puts(lic.nil? ? '// Unspecified license.' : "// Under #{lic2id[lic]}.")
      prev = lic
    end
    h.puts
    h.puts "// Origin: #{piece['header']}"
    h.puts(piece['header_content'])
  end
  generated.each_pair do |typename, object|
    h.puts %Q(
// #{typename}
#{object[:extern].join("\n")}

#{object[:typedef].join("\n")}

#{object[:class].join("\n")}
)
  end
  h.puts %Q(
} // namespace #{spec['namespace']}

#endif)
  h.close
  return spec['header']
end

def make_source(spec, piece_names, generated, lic2id, header_name)
  h = File.new(spec['source'], 'w')
  h.puts %(// Auto-generated file. Do not edit.
#{license_block(lic2id)}

#define INCLUDED_FROM_GENERATED_SOURCE 1
#include "#{header_name}"
#undef INCLUDED_FROM_GENERATED_SOURCE
#{unique_in_order(piece_names, 'source_includes').join("\n")}

using namespace #{spec['namespace']};
)
  prev = nil
  piece_names.each do |name|
    piece = $PIECES[name]
    next if piece['source_stored'].nil?
    lic = piece['license_stored']
    if lic != prev
      h.puts
      h.puts(lic.nil? ? '// Unspecified license.' : "// Under #{lic2id[lic]}.")
      prev = lic
    end
    h.puts
    h.puts "// Origin: #{piece['source']}"
    h.puts(piece['source_content'])
  end
  generated.each_pair do |typename, object|
    h.puts %(
// #{typename}
#{object[:extern_src].join("\n")}
)
  end
  h.close
  return spec['source']
end

specs.each_pair do |name, spec|
  defaults('specification', spec)
  default(spec, 'name', name)
  spec['header'] = "#{spec['name']}.#{spec['header_extension']}" if spec['header'].nil?
  spec['source'] = "#{spec['name']}.#{spec['source_extension']}" if spec['source'].nil?
  spec['generate'].each_pair do |typename, gen|
    unless spec['types'].key? typename
      aargh("#{name} generate #{typename} has no match in types: #{spec['types'].keys.sort.join(' ')}", 4)
    end
    defaults('generate', gen)
  end
  spec['types'].each_pair do |typename, object|
    unless spec['generate'].key? typename
      puts "#{name} #{typename} deleted since it has no match in generate: #{spec['generate'].keys.sort.join(' ')}"
      spec['types'].delete typename
      next
    end
    reqs = []
    object.each_pair do |field, desc|
      defaults('types', desc)
      if spec['generate'][typename]['parser']
        check_given(spec, 'types', 'format', "#{name} #{typename} #{field} has no 'format'.")
        desc['format'] = [ desc['format'] ] unless desc['format'].is_a? Array
        reqs.concat desc['format']
      end
      gen = spec['generate'][typename]
      if gen['writer'] && !gen['parser'] # Parser sets defaults later.
        unless desc['required']
          check_given(desc, 'types', 'checker', "#{name} #{typename} #{field} has no 'checker'.")
        end
        check_given(desc, 'types', 'accessor', "#{name} #{typename} #{field} has no 'accessor'.")
      end
    end
    object[:requires] = reqs.uniq
  end
  spec['types'].each_pair do |typename, object|
    object.each_pair do |field, desc|
      next unless field.is_a? String
      next unless spec['generate'][typename]['parser']
      desc['format'].each do |f|
        unless f.is_a? String
          aargh("#{name} #{typename} #{field} format not string.", 4)
        end
        if $PIECES.key? f
          object[:requires].push f
          next if $PIECES[f]['external']
          aargh("#{name} #{typename} #{field} format #{f} internal.", 4)
        end
        if spec['generate'].key? f
          next if spec['generate'][f]['parser']
          aargh("#{name} #{typename} #{field} format #{f} no parser.", 4)
        end
        if spec['types'].key? f
          aargh("#{name} #{typename} #{field} format #{f} not generated.")
        else
          aargh("#{name} #{typename} #{field} format #{f} not found: #{spec['types'].keys.sort.join(' ')}")
        end
        exit(4)
      end
    end
  end
end

def classify_expression(expr)
  # Simple but good enough for now. If expression gets confused with method,
  # add space in any place where it does not affect the meaning.
  return :expression if expr.nil? # Will go unused in this case.
  return :expression if expr.include? ' '
  return :expression if expr.include?('.') || expr.include?('->')
  return :method if expr.end_with? '()'
  :member
end

def write_function(spec, typename)
  object = spec['types'][typename]
  all_req = true
  object.each_value do |desc|
    all_req = false unless desc['required']
  end
  lines = [ %(
#if !defined(INCLUDED_FROM_GENERATED_SOURCE)
template<typename Sink>
void Write(Sink& S, const #{typename}& Value, std::vector<char>& Buffer) {
    char c = '{';
    S.write(&c, 1);) ]
  lines.push('    bool separated = true;') unless all_req
  prev_req = nil
  fields = object.keys
  # If write order is ever something other than the key one, change it here.
  fields.each do |field|
    desc = object[field]
    fill = ''
    unless desc['required']
      lines.push "    if (Value.#{desc['checker']}) {"
      fill = '    '
    end
    unless prev_req.nil?
      if all_req || prev_req
        lines.push "#{fill}    c = ',';"
        lines.push "#{fill}    S.write(&c, 1);"
      elsif !prev_req.nil?
        lines.push "#{fill}    if (!separated) {"
        lines.push "#{fill}        c = ',';"
        lines.push "#{fill}        S.write(&c, 1);"
        lines.push "#{fill}    }"
      end
    end
    lines.push "#{fill}    Write(S, #{typename}_#{field}, Buffer);"
    lines.push "#{fill}    c = ':';"
    lines.push "#{fill}    S.write(&c, 1);"
    lines.push "#{fill}    Write(S, Value.#{desc['accessor']}, Buffer);"
    lines.push("#{fill}    separated = false;") unless all_req || field == fields.last
    lines.push('    }') unless desc['required']
    prev_req = desc['required']
  end
  lines.push %(    c = '}';
    S.write(&c, 1);
}
#endif // INCLUDED_FROM_GENERATED_SOURCE
)
  lines.join("\n")
end

specs.each_pair do |name, spec|
  needed = []
  needed.concat spec['requires']
  spec['generate'].each_key do |typename|
    next unless spec['types'][typename].key? :requires
    needed.concat spec['types'][typename][:requires]
    needed.push 'ParseObject'
    spec['types'][typename].delete :requires
  end
  if needed.empty?
    unless spec['full']
      puts "#{name} needs nothing and not full, skipped."
      next
    end
    needed = $PIECES.keys
  else
    if spec['full']
      needed.concat($PIECES.keys)
    else
      $PIECES.each_pair do |name, piece|
        needed.push(name) if piece['writer']
      end
      reqs = []
      needed.each { |typename| reqs.concat $PIECES[typename]['requires'] }
      reqs.uniq!
      while true
        s = reqs.size
        added = []
        reqs.each { |typename| added.concat $PIECES[typename]['requires'] }
        reqs.concat added
        reqs.uniq!
        break if s == reqs.size
      end
      needed.concat reqs
    end
    spec['generate'].each_value do |gen|
      needed.push('String') if gen['parser']
    end
    needed.uniq!
  end
  parserpool_substitutions(needed, spec['namespace'])
  needed = arrange_needed(needed)
  lic2id = licenses(needed)
  generated = { }
  spec['generate'].each_pair do |typename, gen|
    object = spec['types'][typename]
    out = {
      forward: [],
      typedef: [],
      extern: [],
      extern_src: [],
      class: []
    }
    if gen['parser']
      out[:forward].push "class #{typename};"
      keyvalues = []
      values = []
      names = []
      object.each_pair do |field, desc|
        sub = "#{typename}_#{field}"
        # Field name string constant.
        out[:extern].push "extern const char #{sub}[];"
        out[:extern_src].push "const char #{spec['namespace']}::#{sub}[] = \"#{field}\";"
        k = desc['format'].size - 1
        f = desc['format'][k]
        p = $PIECES[f]
        out[:typedef].push "typedef #{p['parsername']} #{sub}_#{k};"
        while k.positive?
          k -= 1
          f = desc['format'][k]
          p = $PIECES[f]
          out[:typedef].push "typedef #{p['parsername']}<#{sub}_#{k + 1}> #{sub}_#{k};"
        end
        keyvalues.push "#{desc['required'] ? 'Required' : ''}Key#{desc['format'].size > 1 ? 'Container' : ''}Value<#{sub},#{sub}_0>"
        out[:typedef].push "typedef #{keyvalues.last} #{sub}_KeyValue;"
        values.push "Value<#{sub}_0>"
        names.push field
        default(desc, 'accessor', "#{field}()")
        desc[:access_type] = classify_expression(desc['accessor'])
        default(desc, 'checker', "#{field}Given()")
        desc[:check_type] = classify_expression(desc['checker'])
      end
      out[:typedef].push "typedef KeyValues<#{keyvalues.join(',')}> #{typename}_KeyValues;"
      out[:typedef].push "typedef NamelessValues<#{values.join(',')}> #{typename}_NamelessValues;"
      out[:typedef].push "typedef ParseObject<#{typename}_KeyValues,#{typename}_NamelessValues> #{typename}_Parser; // Parse with an instance of this."
      out[:class].push %(
class #{typename} {
public:
#{(names.map { |n| "    typedef #{values[names.find_index(n)]}::Type #{n}Type;" }).join("\n")}
    #{typename}_Parser::Type values;

#{(names.map { |n| "    bool #{n}Given() const { return std::get<#{names.find_index(n)}>(values).Given(); }" }).join("\n")}

#{(names.map { |n| "    #{n}Type& #{n}() { return std::get<#{names.find_index(n)}>(values).value; }" }).join("\n")}
#{(names.map { |n| "    const #{n}Type& #{n}() const { return std::get<#{names.find_index(n)}>(values).value; }" }).join("\n")}
};
)
      out[:class].push write_function(spec, typename) if gen['writer']
      generated[typename] = out
    elsif gen['writer']
      object.each_pair do |field, desc|
        sub = "#{typename}_#{field}"
        out[:extern].push "extern const char #{sub}[];"
        out[:extern_src].push "const char #{spec['namespace']}::#{sub}[] = \"#{field}\";"
        desc[:access_type] = classify_expression(desc['accessor'])
        desc[:check_type] = classify_expression(desc['checker'])
        desc[:tn] = "T_#{field}"
      end
      # Template class for write.
      get_ind = object.keys.select { |k| object[k][:access_type] == :method }
      get_dir = object.keys.select { |k| object[k][:access_type] != :method }
      chk_ind = object.keys.select { |k| object[k][:check_type] == :method && !object[k][:required] }
      tmpl = [ %(
template<#{(object.keys.map { |k| "typename #{object[k][:tn]}" }).join(',')}>
class #{typename}_Template {
private:
#{(get_ind.map { |f| "    #{object[f][:tn]} #{f}_value;" }).join("\n")}

#{(chk_ind.map { |f| "    bool #{f}_given;" }).join("\n")}

public:) ]
      unless chk_ind.empty? # Constructor to set given indicators to false.
        tmpl.push "    #{typename}_Template() : #{(chk_ind.map { |f| "#{f}_given(false)" }).join(', ')} { }"
      end
      tmpl.push(%(
#{(chk_ind.map { |f| "    bool& #{object[f][:checker]} { return #{f}_given; }" }).join("\n")}
#{(chk_ind.map { |f| "    bool #{object[f][:checker]} const { return #{f}_given; }" }).join("\n")}

#{(get_dir.map { |f| "    #{object[f][:tn]} #{f};" }).join("\n")}

#{(get_ind.map { |f| "    #{object[f][:tn]}& #{object[f]['accessor']} { return #{f}_value; };" }).join("\n")}
#{(get_ind.map { |f| "    const #{object[f][:tn]}& #{object[f]['accessor']} const { return #{f}_value; }" }).join("\n")}
};))
      tmpl = tmpl.join("\n")
      # Tweak the looks of output.
      until (tmpl.sub!("\n\n\n", "\n\n")).nil? # Shrink two empty lines to 1.
      end
      tmpl.sub!("private:\n\n", "private:\n")
      tmpl.sub!("public:\n\n", "public:\n")
      tmpl.sub!("private:\npublic:", 'public:') # Drop private if not used.
      tmpl.sub!("\n\n};", "\n};")
      out[:class].push tmpl
      # define check and typedef for template.
      out[:class].push %(
#if defined(#{spec['namespace'].upcase}_#{typename.upcase}_TYPE)
typedef #{spec['namespace'].upcase}_#{typename.upcase}_TYPE #{typename};
#endif
)
      out[:class].push write_function(spec, typename)
      generated[typename] = out
    end
  end
  puts "#{name}: #{generated.keys.join(' ')} #{needed.join(' ')}"
  hdr = make_header(spec, needed, generated, lic2id)
  src = make_source(spec, needed, generated, lic2id, hdr)
  puts "  Header: #{hdr}, source: #{src}"
end
